articles/urls.py
from django.urls import path
from articles import views

app_name = "articles"

urlpatterns = [
    path('index/', views.index),
    path('dinner/', views.dinner, name='dinner'),
    #string으로, url변수명을 name으로 해서 아이디나 이름을 먼저 받는다. 
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'),
    path('<int:pk>/', views.detail, name='detail'),
    #int(숫자)를 pk라는 변수명에 저장해서 건네주기
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),


]

startdjango/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls', namespace='articles')),
    # path('foods/', include('foods.urls')),
]

articles/models.py
from zipapp import create_archive
from django.db import models

# create your models!

class Review:
    title = ''
    content = ''
    user = ''

    def __init__(self, content=content, title=title, user=user):
        #인스턴스에 바로 값을 집어넣을 수 있도록 __init__이용해서 self인자(기본)와, 필요한 데이터 인자를 넣어줌.
        #왼쪽이 키값, 오른쪽이 실제 값이 들어오는 변수명.
        self.content = content
        #self의 content = 위에서 들어온 content실제 값.
        self.title = title
        self.user = user

review1 = Review(title="저의 인생영화", content="인생은 아름다워", user="sun")
#review1은, Review클래스 안에, title, content, user가 입력되어 생성된 인스턴스. 
#키와 변수명을 위에서 정의해줬기 때문에 순서가 섞여도 되지만, 정의하지 않은 경우엔 꼭 순서대로 입력해주어야 한다. 가능한 이렇게 사용할것


class Article(models.Model):
    #models.Model 상속, id는 자동으로 만들어짐.
    title = models.CharField(max_length=10)
    #title은, models에서 가져온 글자수 10까지의 field
    content = models.TextField()
    #content는 많은 양의 글자를 받을 수 있는 field
    created_at = models.DateTimeField(auto_now_add=True)
    #created_at은 models의 DateTimeField(날짜 및 시간 필드)를 가져와서, uto_now_add=True(생성시 시각 자동 추가)되도록 하겠다.

foods/models.py
from django.db import models

# Create your models here.

articles/views.py
from django.shortcuts import render, redirect
import random
from .models import Article
#같은 폴더(앱)의 models안의 Article 모델 가져오기

# Create your views here.
def index(request):
    return render(request, 'index.html')

def dinner (request):
    menus = [{"name":'족발', "price":30000}, {"name":'햄버거', "price":5000}, {"name":'치킨', "price":20000}, {"name":'초밥', "price":15000}]
    #보통 이렇게 딕셔너리 안에 리스트로 담겨있는 경우가 많다.
    pick = random.choice(menus)
    #pick은 menus중에서 하나를 랜덤으로 골라주는 것. 고른 값이 pick 안에 들어감.
    articles = Article.objects.order_by('-pk')
    #Article모델을 pk(등록 아이디)의 역순으로 불러오기(장고 orm문법)
    context = {
        'pick':pick,
        'menus':menus,
        #menus안에 있는 것들을 for문으로 돌려주기 위해 contex안에 menus를 담아서 html에 넘겨준다. 
        'articles':articles,
    }
    #views.py에서 html로 데이터를 넘겨주기 위해 context라는 것을 사용함. 딕셔너리 형태로 만들고, 그 안에 키값:밸류값을 넣어준다.
    return render(request, 'dinner.html', context)
    #render에도 request, html, context를 실어줘야 한다.

def review(request):
    return render(request, 'review.html')

def create_review(request):
    content = request.POST.get('content')
    #request로 받은 것 중 post메소드 일때, 그 데이터 안에서 content라는 이름만 받아오기. (html에 name=content인 데이터 있음)
    title = request.POST.get('title')
    article = Article(title = title, content = content)
    # article이란 인스턴스 안에 위에 임포트했던 Article모델의 content, title을 받아온다.
    article.save()
    # Article 모델에 대한 인스턴스이기 때문에 특별한 기능들이 제공된다. 그 중 하나가 save이며, 인스턴스의 내용을 db에 알아서 저장되도록 한다.

    return redirect('articles:detail', article.pk)
    #저장까지 모두 끝난 후, detail페이지로 옮겨가도록 한다.


def detail(request, pk):
#pk를 받아옴으로써 url에 입력된 숫자를 가져와 db에 저장된 아이디를 조회함.
    article = Article.objects.get(pk=pk)
    #article이란 변수 안에 Article모델의 pk를 가져옴.(request해온 pk와 일치하는)
    context = {
        'article' : article
    }
    return render (request, 'detail.html', context)
    #첫번째 인자 request, 두번째 template, 세번째 article이 담긴 context를 실어서 보내준다.

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    #detail과 동일하게 article db에서 불러오기

    if request.method == 'POST':
    #요청 방식이 post일 때만
        article.delete()
        #Article모델 안에 정의된 delete를 실행한다.
    return redirect('articles:dinner')
    #지우고 나면 리스트 페이지로 돌아가도록

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    #edit도 delete처럼 어느 한 글을 쏙 골라서 수정하는 것이기 때문에 게시글의 pk를 받아와야함.
    context = {
        'article' : article,
    }
    return render(request, 'edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    #(파이썬에서)article의 타이틀을, post요청된 edit.html에서의 name = title로 바꾼다.
    article.content = request.POST.get('content')
    article.save()
    #db에 수정된 정보를 저장한다.
    return redirect('articles:detail', article.pk)
    

foods/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>오늘뭐먹지?</title>
    <!-- 부트스트랩 CSS -->
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" 
        crossorigin="anonymous"
    >
    
</head>
<body class="container">
    {% block content %} {% endblock %}
    <!-- #block안에 어떠한 콘텐츠를 가져와 넣을 것을 표시 -->

    <!-- 부트스트랩 JS -->
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" 
        crossorigin="anonymous"
    ></script>

</body>
</html>

articles/templates/detail.html
{% extends 'base.html' %} {%  block content %}

<h2 class="text-center">DETAIL</h2>
<h3>{{ article.pk }}번째 글</h3>
<br />
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<p>작성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
<!-- date:"SHORT_DATE_FORMAT"는 필터 기능. 날짜를 일/월/년(ex. 21/05/2020)형식으로 출력함. -->
<form action="{% url 'articles:delete' article.pk %}" method="POST">
<!-- method 미작성시 디폴트 get으로 감. -->
    {% csrf_token %}
    <button class="btn btn-danger">DELETE</button>
</form>
<a href="{% url 'articles:edit' article.pk %}" class="btn btn-primary">EDIT</a> <br />
<a href="{% url 'articles:dinner' %}">[back]</a>
<br />

{%  endblock %}

articles/templates/dinner.html
{% extends 'base.html' %} {% block content %}
<!-- #extends로 이 파일이 base.html안에 들어갈 것임을, 그리고 block content가 시작됨을 알려줌. -->
<h1>오늘 저녁은 {{pick.name}}입니다</h1>
<!-- #중괄호 두 개를 이용해 pick값을 받아 넣어줌. -->
<h1>메뉴 리스트</h1>
<ul>
    <!-- #숫자가 달리지 않은, 앞에 .이 찍힌 리스트를 사용 -->
    {% for menu in menus %}
    <!-- #파이썬 문법과 똑같은 for문 -->
    <li>{{menu.name}}{{menu.price}}</li>
    <!-- #menus를 for문을 돌려서 그 안의 name값만 가져오기. -->
    {% endfor %}
    <!-- #for문 끝 -->
<ul>

{% if pick.price > 20000 %}
<!-- #만약 pick의 price가 20000이상이라면 -->
<p>비싸다!</p>
<!-- #비싸다! 를 출력해줘. -->
{% elif pick.price > 10000 %}
<p>해볼만하다!</p>
{% else %}
<p>맛있겠다!</p>
{% endif %}
<!-- #'>'양 옆 띄어쓰기 주의. -->

<h1>리뷰 리스트</h1>
<a href="{% url 'articles:review' %}">[리뷰 작성하기]</a>
{% for article in articles %}
<!-- #리뷰들을 모두 가져오기 위해 반복문 사용 (template문법으로), articles 앱 안의 article 모델에서 하나하나 꺼내주기. -->
    <p>글 번호 : {{article.pk}}</p>
    <!-- pk는 자동으로 만들어짐(고유아이디) -->
    <p>글 제목 : {{article.title}}</p>
    <p>글 내용 : {{article.content}}</p>
    <a href="{% url 'articles:detail' article.pk %}">[detail]</a>
    <!-- [detail]버튼을 누르면 articles의 detail url로 가되 인자를 article.pk로 넣어달라. -->
    <hr>
{% endfor %} {% endblock %}
<!-- for 문 끝 / 여기까지 base.html에 붙여넣음. block끝 -->

articles/templates/edit.html
{% extends 'base.html' %} {%  block content %}

<h1 class="text-center">EDIT</h1>
<form class="form-group" action = "{% url 'articles:update' article.pk%}" method = "POST">
    {% csrf_token %}
    <label for="title">Title: </label>
    <input class="form-control" type="text" name="title" value="{{ article.title }}"><br />
    <!-- 값으로 기존 article의 제목을 받아옴 -->
    <label for="content">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5">{{ article.content }}</textarea><br />
    <input type="submit">
</form>

{%  endblock %}

articles/templates/index.html
    <h1>거북이 화이팅!!</h1>

articles/templates/review.html
{% extends 'base.html' %} {%  block content %}
<!-- base.html 불러오고/ 어느 block이 들어가는지 명시함 -->

<form 
    class = "form-group" action = "{% url 'articles:create_review' %}" method = "POST">
    <!-- action = "articles의 create_review페이지로 보낼 것이다"  -->

    {% csrf_token %}
    <!-- 보안을 위해 삽입 -->
    <label for = "title">Title: </label>
    <input class = "form-control" type = "text" name = "title" /> <br />
    <label for = "content">Content: </label>
    <textarea class = "form-control" name = "content" cols="30" rows="5"></textarea>
    <br />
    <input type="submit" />

</form>

{% endblock %}

articles/templates/review_result.html
<h1>보내서 받은 내용은 {{ content }}입니다. </h1>
<!-- #views.py의 context중에서 content만 뽑아 template문법으로 나타내주기 -->